# -*- coding: utf-8 -*-
"""drs_prot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https:\\colab.research.google.com\drive\1tESYnki6lZXnm7DvTY8n67xR6b5rlQN-

# Import
"""

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import pandas as pd
import numpy as np
import re
import os
import copy
import pprint

import MeCab
import ipadic

from sklearn.multiclass import OneVsRestClassifier
from sklearn import svm, decomposition
from sklearn.svm import SVC, OneClassSVM
from sklearn.decomposition import PCA

from joblib import dump,load


import torch
from torch.utils.data import DataLoader
from transformers import BertJapaneseTokenizer, BertForSequenceClassification,BertTokenizer
import torch.nn as nn

MODEL_NAME = 'tohoku-nlp/bert-base-japanese-whole-word-masking'
tokenizer = BertJapaneseTokenizer.from_pretrained(MODEL_NAME)

path_Content_points = '../data/data_prot/Rules/Content_points.csv'
df_Content_points = pd.read_csv(path_Content_points)
"""# Programs

## Parsing Input
"""
#文章を文単位で分割
def parse_Paragraph(paragraph):
    """
    文章を文単位に分割し、リストとして返す。

    Returns:
      list[str]:  句点で終わる文のリスト
    """
    if not re.search(r'[。．]\s?|\. ?|$', paragraph):
        paragraph += '。'
    sentences = re.split(r'(?:。|．|\. ?|$)', paragraph)
    # 空白や空文字だけの要素を除外し、句点を補う
    res = [s.strip() + '。' for s in sentences if s.strip()]
    return res

def parse_Sentence(sentence):
  """
  MeCabを使用して1文を分かち書き

  Returns: MeCabが形態素解析した結果を文字列として返す。
          品詞情報が含まれる。
  """  
  m = MeCab.Tagger()  
  parsed = m.parse(sentence)
  return parsed

def parse_Parag_to_Word(paragraph):
  """
  MeCabを使用して文章を分かち書き

  Returns: MeCabが文章を形態素解析した結果を文字列のリストとして返す。
            品詞情報が含まれる。
  """
  sentences = parse_Paragraph(paragraph)
  word_parsed_paragraph = [[p.split('\t') for p in parse_Sentence(s).split('\n')[:-2]] for s in sentences]
  return word_parsed_paragraph


"""## BERTを使用した要素分類(import Parsing Input)"""

### Prediction"""
def predict_Sentence_attr(vec):
  """
  ベクトル化された1文を学習済みBERTモデルを使用して要素分類を行う。

   与えられたベクトルをモデルに入力し、"claim","ground","undifine"に分類し、返す。

  Args:
    vec (touch.Tensor): モデルに入力するベクトル化された文
  
  Returns:
    str: 予測されたクラス名("claim","ground","undifine")
  """
  model = BertForSequenceClassification.from_pretrained('../data/model_transformers_Element_classification_forMaC')
  model.eval()  

  with torch.no_grad():
    outputs = model(vec)
    logits = outputs.logits
    predicted_class = torch.argmax(logits, dim=1).item()
  
  class_map = {
    0: 'claim',
    1: 'ground',
    2: 'ground'
  }
  prediction = class_map.get(predicted_class, 'undifine')

  return prediction

def make_vec(sentence):
  """
  トークナイザを用いた文のベクトル化

  Args:
    sentence (str): ベクトル化を行う対象の1文

  Returns: 
    touch.Tensor: バッチサイズ１のテンソル形式で、トークンIDが格納されている。

  """
  input_ids = tokenizer.encode(sentence, add_special_tokens=True)
  input_ids = torch.tensor(input_ids).unsqueeze(0) 
  return input_ids

def make_vec_2sentences(first_sentence, second_sentence):
  """
  トークナイザを用いた2文のベクトル化

  2文をまとめてベクトル化

  Args: 
    first_sentence (str): ベクトル化を行う2文のうち1分目
    second_sentence (str): ベクトル化を行う2文のうち2文目

  Returns:
    touch.Tensor: バッチサイズ1のテンソル形式で、トークンIDが格納されている。
  """
  input_ids = tokenizer.encode(first_sentence,second_sentence,add_special_tokens=True)
  input_ids = torch.tensor(input_ids).unsqueeze(0)  # バッチサイズ1で入力
  return input_ids

def content_classification(paragraph):
  """
  入力として与えられた文章に対して要素分類を行う。

  Args:
    paragraph (str): 処理対象の文章
  
  Returns: 
    list[str]: 文章内のそれぞれの文に対応する予測された要素分類結果のリスト
  """

  parsed = parse_Paragraph(paragraph)
  arr_attr = []
  for p in parsed:
    vec = make_vec(p)
    arr_attr.append(predict_Sentence_attr(vec))
  print(arr_attr)
  return arr_attr

"""加点行列"""
def Content_addmat(arr_content, matsize, df_content_points):
  """
  指定された要素分類済みの文章から加点行列を作成。
  論証構造図作成のための加点行列

  Args:
    arr_content (list): 加点行列を作成するための、要素分類の結果のリスト
    matsize: 生成する行列のサイズ
    df_content_points: 関連ポイントを格納したデータフレーム。

  Strings:
    np.ndarray: 生成された加点行列
  """

  print("arr_content:"+str(arr_content))
  if len(arr_content) > matsize:
    arr_content = arr_content[:matsize]
  points_mat = np.zeros((matsize, matsize), dtype=int)
  for i in range(matsize):
    for j in range(i+1, matsize):
      if i != j:
        print("arrcontent[i]:"+str(arr_content[i]))
        print("arrcontent[j]:"+str(arr_content[j]))
        res = df_content_points[df_content_points['from'].isin([arr_content[i]])]

        res = res[res['to'].isin([arr_content[j]])]
        print("res:"+str(res))
        points_mat[i][j] = res["point"]+i-j+1
  return points_mat

"""### 加点行列をつくる"""
#search_ConjuctionからDataFrame.iterrows()でiterateしてattrでrsearch_Rulesから抽出適用・構造候補の加点行列を作る
def Conjuction_addmat(rules, matsize, cur, arr_attr, priority):
  points_mat = np.zeros((matsize, matsize), dtype=int)
  rules['from_start'] = rules['from_start'].fillna(-cur)
  rules['from_end'] = rules['from_end'].fillna(-cur)
  rules['to_start'] = rules['to_start'].fillna(-cur)
  rules['to_end'] = rules['to_end'].fillna(matsize)
#  #print(rules)
  for index, rule in rules.iterrows():
#    #print(rule)
    point = int(abs(rule['point'])*(priority))
    adder_fromstart = cur + int(rule['from_start'])
    adder_fromend = cur + int(rule['from_end'])+1
    adder_tostart = cur + int(rule['to_start'])
    adder_toend = cur + int(rule['to_end'])+1
    
    if np.isnan(rule['if_loc']) != True:
      #print("drs-prot:158\n",rule,"\n", cur+int(rule['if_loc']), arr_attr)
      if cur+int(rule['if_loc']) < matsize:
        if arr_attr[cur+int(rule['if_loc'])] == rule['if_is']:
          ##print(point,"points [",adder_fromstart,":",adder_fromend,"] to [",adder_tostart,":",adder_toend,"] with \"", rules['attr'].tolist()[0],"\"")
  #        #print(points_mat[adder_fromstart:adder_fromend][adder_tostart:adder_toend])
          points_mat[adder_fromstart:adder_fromend,adder_tostart:adder_toend] += point
          #points_mat[adder_tostart:adder_toend,adder_fromstart:adder_fromend] += point
    else:
      ##print(point,"points [",adder_fromstart,":",adder_fromend,"] to [",adder_tostart,":",adder_toend,"] with \"", rules['attr'].tolist()[0],"\"")
      points_mat[adder_fromstart:adder_fromend,adder_tostart:adder_toend] += point
      #points_mat[adder_tostart:adder_toend,adder_fromstart:adder_fromend] += point
    print(points_mat,"\n")
  return points_mat

#Conjuction_addmat(rules, 5, 3, ["ground", "ground", "ground", "ground", "claim"])

def Paragraph_to_Conjuction_addmat(df_conjuction_attr, df_conjuction_points, sentences, arr_content, df_conjuction_priority_arr):
  len_sentence = len(sentences)
  addmat = np.zeros((len(sentences), len(sentences)), dtype=int)
  cases = pd.DataFrame({'matrix':[addmat], 'label':['']})

  return cases

"""# 関係分類BERT"""
def relationship_Classification(paragraph, matsize):
  """
  入力として与えられた文章に対して関係分類を行う。

  Args:
    paragraph (str): 処理対象の文章
    matsize: 生成する行列のサイズ
  
  Returns: 
    list[str]: 文章内のそれぞれの文の組み合わせに対応する予測された関係分類結果

  """
  sentences = parse_Paragraph(paragraph)
  points_mat = np.zeros((matsize, matsize), dtype=int)
  model = BertForSequenceClassification.from_pretrained('../data/Ja_sup_model_transformers_forMaC')
  model.eval()  # 推論モードに切り替え
  for i in range(matsize):
    for j in range(i+1, matsize):
    # モデルへの入力と推論
      vec=make_vec_2sentences(sentences[i],sentences[j])
      with torch.no_grad():
        outputs = model(vec)
      
  # 結果の解釈
      logits = outputs.logits
      probabilities = nn.functional.softmax(logits, dim=-1)
      print(probabilities)
      support = probabilities[0][1]/10
      support = int(support)
      points_mat[i][j]=support
  return points_mat

#生の文章(paragraph)と結論の位置(target)から点数を出す
def Point_matrix(paragraph, target):

  def Reshape_sentence(sentences):
    words = []
    i=1  
    for sentence in sentences:
      words.append(""+str(i)+". "+''.join([w for w in [sentence[n][0] for n in range(len(sentence)-1)]]))
      i+=1
    return words

  #print(paragraph, target)

  #文を分かち書き
  sentences = parse_Parag_to_Word(paragraph)
  len_sentence = len(sentences)
  if target == -1:
    return [], [], [], [], Reshape_sentence(sentences)

  #文章の頭から指定の文まで抜き出し
  sentence_full = copy.copy(sentences)
  if len_sentence >= target:
    sentences_ = sentences[:target]
    len_sentence = len(sentences)
  elif target > len_sentence:
    sentences_ = sentences
    target = len_sentence
  
  words = Reshape_sentence(sentences_)
  sentence_full = Reshape_sentence(sentence_full)

  #点数の行列
  points_mat = np.array([[50]*target for i in range(target)])

  #要素分類
  print("---------------要素分類------------------------------------------------")
  arr_content = content_classification(paragraph)
  arr_content.append('claim')
  #arr_content = ["ground", "ground", "ground", "claim", "claim", "claim", "claim", "claim", "ground", "claim"]
  content_addmat = Content_addmat(arr_content, target, df_Content_points)
  print(arr_content,"\n",content_addmat)
  points_mat += content_addmat

  print("---------------関係分類------------------------------------------------")
  relation_point=relationship_Classification(paragraph, target)
  points_mat += relation_point
  #relation_point['matrix'] = relation_point['matrix'].map(lambda x: x + points_mat)
  print(relation_point)
  #接続詞の加点行列
  print("---------------接続詞------------------------------------------------")
  conjuction_addmat = Paragraph_to_Conjuction_addmat(df_conjuction_attr, df_conjuction_points, sentences_, arr_content, df_conjuction_priority_arr)
  conjuction_addmat['matrix'] = conjuction_addmat['matrix'].map(lambda x: x + points_mat)
  print(conjuction_addmat)
  
  print("---------------------------------------------------------------------")

  res_mat = []
  res_label = []
  i = 0
  for index, row in conjuction_addmat.iterrows():
    print(row['label'],row['matrix'],"\n")
    res_mat.append(row['matrix'].tolist())
    res_label.append(row['label'])
    i+=1
  print(arr_content)
  return res_mat, res_label, words, arr_content, sentence_full

  
if __name__ == '__main__':
  Point_matrix("図26、図27より、バッファサイズが大きくなる程実行時間が短くなることがわかる。さらに、それぞれの近似曲線より、バッファサイズをx、実行時間をyとすると、両者の関係はy=a/x(aはある特定の定数)という方程式で近似的に表せることができ、実行時間はバッファサイズに反比例していることがわかる。また図27より、read、writeによる実装よりも、fread、fwriteによる実装の方が実行時間が速いことがわかる。実行時間がバッファサイズに反比例したのは、次のような理由が考えられる。cでは、ファイルの内容がバッファサイズごとに読み取り・書き込みが行われる。その処理の回数はバッファサイズに反比例する。よって読み取り・書き込みの回数が増えることによって実行時間が増えると考えられる。read、writeによる実装よりも、fread、fwriteによる実装の方が実行時間が速いのには、以下のような理由が考えられる。cは、両者とも同じバッファサイズで実行しているが、システムコールread、write関数の呼び出し回数が大きく違う。これによって両者の実行時間の違いが出ていると考えられる。", 10)

 